name: Apply Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workspace:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  apply:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    defaults:
      run:
        shell: pwsh
        working-directory: ./Terraform

    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Project
        uses: actions/download-artifact@v3
        with:
          name: published-app
          path: ./Terraform/${{ github.run_id }}.zip
          if-no-files-found: error

      - name: Initialize
        id: init
        run: |
          terraform init -no-color
      
      - name: Set Workspace
        id: workspace
        run: |
          terraform workspace select ${{ inputs.workspace }}
      
      - name: Create Plan
        id: plan
        run: |
          terraform plan -out=tfplan -var="published_app_location=.\${{ github.run_id }}.zip" | Out-Null
          terraform show -no-color tfplan

      - name: Apply Plan
        id: apply
        run: |
          terraform apply -no-color -auto-approve tfplan
