name: Build App

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
    secrets:
      user:
        required: true
      pat:
        required: true

jobs:
  build-publish:
    name: Building...
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.project }}

    steps:
      - name: Checking out repository...
        id: checkout
        uses: actions/checkout@v3

      - name: Authenticating to Github...
        run: dotnet nuget add source --username ${{ secrets.user }} --password ${{ secrets.pat }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rxhonesty/index.json"

      - name: Building app...
        id: build
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet publish --no-build --configuration Release --output ./publish
      
      - name: Compressing...
        run: |
          Compress-Archive ./publish/* ${{ github.run_id }}.zip
      
      - name: Uploading artifact...
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./${{ inputs.project }}/${{ github.run_id }}.zip
          if-no-files-found: error