name: Build App

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string

jobs:
  build-publish:
    name: Building...
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ inputs.project }}

    steps:
      - name: Checking out repository...
        id: checkout
        uses: actions/checkout@v3

      - name: Building app...
        id: build
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet publish --no-build --configuration Release --output ./publish
      
      - name: Compressing...
        run: |
          Compress-Archive ./publish/* ${{ github.run_id }}.zip
      
      - name: Uploading artifact...
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./${{ inputs.project }}/${{ github.run_id }}.zip
          if-no-files-found: error